---
# Configuraci√≥n de router para AlmaLinux

- name: "Habilitar IP forwarding"
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes

- name: "Habilitar IPv6 forwarding"
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: yes

- name: "Configurar reglas de firewall para routing"
  firewalld:
    masquerade: yes
    zone: public
    permanent: yes
    state: enabled
    immediate: yes
  when: firewall_masquerade | default(false)
