$ANSIBLE_VAULT;1.2;AES256;proyecto-so
37663464653332386464316664336662396630366339353733666238666365376137326334363033
3132633765343364306366383531393439653734343938380a306236666564646335633435306535
38363963663439373630363865343237303461656134613066313038343063653164353761333131
3632313564336331660a316135353166363436643265613135386566333565653832613635313737
31356131616261663266626539326365333936343637316235663366393232346131353030313065
63316634383763313539346263353830323466366334643330663062663265353935373434353537
38343364326464646631666663626630313166613861333566626530373762346563363361393733
34643836323431343930366261346361383436663263353563353438653462343434656532613837
38633834626532343036306430653761343061376363373264663565626332623333663535316131
32333066303339383530623264616530343861313532313636633334613732383533616633303839
32313137336236336661613835663966666336623165633932396439663634343165333335316263
66613535636436356161653634633030333965373362623830373437643864373537646237386661
62663135316237353961333164616432316435616666616561306261383234366539616135636437
38666530333135336530616434383532346637326439366333306433336632363632616333346334
64643136376337646639353730613238663336343466383431363434356136613831303530373330
36663437353733343332623533336132623830666339646334613330663765623734303037623138
6262
