---
# defaults for DHCPv6 (Kea)

dhcpv6_interface: "ens37"
dhcpv6_subnet: "2025:db10:20::/64"
dhcpv6_pool: "2025:db10:20::100-2025:db10:20::200"
dhcpv6_dns_servers:
  - "2025:db10:20::1"
dhcpv6_preferred_lifetime: 3600
dhcpv6_valid_lifetime: 7200
dhcpv6_renew_timer: 900
dhcpv6_rebind_timer: 1800
dhcpv6_subnet_id: 1

# Kea paths
dhcpv6_config_dir: "/etc/kea"
dhcpv6_config_path: "/etc/kea/kea-dhcp6.conf"
dhcpv6_service_name: "kea-dhcp6"

# Package
dhcpv6_package_name: "kea"

# Lease database (memfile)
dhcpv6_lease_db_type: "memfile"
dhcpv6_lease_db_path: "/var/lib/kea/kea-leases6.csv"
dhcpv6_lfc_interval: 3600
dhcpv6_lease_db_persist: true
